config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

ApapBranding::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :logos

end

app/models/logo.rb
class Logo < ActiveRecord::Base

  has_attached_file :picture, 
                    :styles => {
                      :thumb => "100x100#",
                      :filtered => { :processors => [:crop_rotate, :brightness] },
                      :multiplied => { :processors => [:crop_rotate, :multiply] }
                    },
                    :path => "./public/system/#{Rails.env.to_s}/logos/pictures/:id/:style/:filename",
                    :url => "/system/#{Rails.env.to_s}/logos/pictures/:id/:style/:filename"
  

  def self.get_recent_pictures
    
    # # 이후 고프로에서 땡겨오는 부분이 여기 들어 감! 땡겨오고 바로 지움. 
    # test_file = Rails.root.join('spec', 'fixtures', 'logo.jpg')
    # l.picture = Rack::Test::UploadedFile.new(test_file, "image/jpg")
    logos = []

    files = Dir.glob(File.join("/home/deployer/snapshots", "*"))
    files.each do |file|
      l = Logo.new
      tt = file.split("_")[1].split('-').join('')
      l.pictured_at = DateTime.new(tt[0..3].to_i, tt[4..5].to_i, tt[6..7].to_i, tt[8..9].to_i, tt[10..11].to_i, tt[12..13].to_i)
      
      l.picture = Rack::Test::UploadedFile.new(file, "image/jpg")

      if l.save
        logos << l 
        File.delete(file)
      end
    end

    return logos
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logos_controller.rb
#encoding: utf-8
class LogosController < ApplicationController
  def index
    @page = params[:page].present? ? params[:page] : 1
    @logos = Logo.order('pictured_at DESC').paginate(:page => @page, :per_page => 20)
  end

  def new
    LogoWorker.perform_async
    
    redirect_to logos_path, :notice => '성공적으로 등록하였습니다.'
  end

  def show
    @logo = Logo.find params[:id]
  end

  def create
    @logo = Logo.new(params[:logo])
    @logo.pictured_at = DateTime.now unless params[:logo][:pictured_at].present?
    
    if @logo.save
      redirect_to logos_path, :notice => '성공적으로 등록하였습니다.'
    else
      redirect_to resquest.referer, :alert => '저장 중 오류가 발생하였습니다.'
    end
  end

  def edit
    @logo = Logo.find params[:id]
  end

  def update
    @logo = Logo.find params[:id]
    #sif @logo.update_attributes(params[:logo])

  end

  def destroy
    @logo = Logo.find params[:id]
    @logo.destroy

    redirect_to logos_path, :notice => '성공적으로 삭제하였습니다.'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApapBranding</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logos/_tab.html.erb
<ul class="nav nav-tabs">
  <li class="<%= 'active' if params[:controller] == 'logos' %>">
    <%= link_to "로고 관리(#{Logo.count})", logos_path %>
  </li>
</ul>

app/views/logos/index.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>

<%= render 'tab' %>
<h2>
  로고 관리
</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>
        촬영일
      </th>
      <th>
        삭제
      </th>
    </tr>
  </thead>
  <tbody>
    <% @logos.each do |logo| %>
      <tr>
        <td>
          <%= link_to logo.pictured_at.strftime("%Y-%m-%d %H:%M"), logo_path(logo) %>
        </td>
        <td>
          <%= link_to '삭제', logo_path(logo), :method => 'delete', :confirm => '정말 삭제하시겠습니까?' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= will_paginate @logos %>

app/views/logos/new.html.erb
<h2>
  새 로고
</h2>

<%= form_for [:admin, @logo], :html => {:class => 'form-horizontal', :multipart => true} do |f| %>
  <div class="control-group">
    <%= f.label :picture, '사진', :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture %>
    </div>
  </div>

  <div class="form-action">
    <%= f.submit '등록하기', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/logos/show.html.erb
<%= flash[:notice] %>
<%= flash[:alert] %>

<%= render 'tab' %>
<h2>
  로고 관리
</h2>

<%= image_tag @logo.picture.url(:filtered), :style => 'width:500px' %>
<%= image_tag @logo.picture.url(:multiplied), :style => 'width:500px' %>